### ISSUE TITLE
Add Name

### ISSUE THREAD

**Issue by fjbardelli** [anexia/drf-multitokenauth#28]
Hi, great job. 
Is it possible to add a name to the token, to be able to identify it in case there are many, and to know which one to eliminate, for example?

**Comment by anx-abruckner** [comment]
@fjbardelli [PR 31](https://github.com/anexia/drf-multitokenauth/pull/31) provides an optional "token_name" field for the MultiToken model. Would this cover what you had in mind or do you require any additional functionality for that new field?

**Comment by anx-abruckner** [comment]
@beachmachine please close this issue - fix from 1 year ago is long merged =)
